# Generated by Django 5.2 on 2025-05-07 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='输入商品的完整名称', max_length=255, verbose_name='商品名称')),
                ('is_seller', models.BooleanField(default=False, verbose_name='是否卖家')),
                ('description', models.TextField(blank=True, help_text='输入商品的详细描述', null=True, verbose_name='商品描述')),
                ('price', models.DecimalField(decimal_places=2, help_text='输入商品的销售价格 (例如: 19.99)', max_digits=10, verbose_name='商品价格')),
                ('stock', models.PositiveIntegerField(default=0, help_text='商品的当前库存量', verbose_name='库存数量')),
                ('is_available', models.BooleanField(default=True, help_text='勾选表示商品当前正在销售', verbose_name='是否在售')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('image', models.ImageField(blank=True, help_text='上传商品的图片', null=True, upload_to='products/%Y/%m/%d/', verbose_name='商品图片')),
                ('user', models.ForeignKey(blank=True, help_text='商品所属的用户或卖家', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品列表',
                'ordering': ['user', 'name'],
            },
        ),
    ]
