# Generated by Django 5.2 on 2025-05-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_seller',
            field=models.BooleanField(default=False, verbose_name='是否卖家'),
        ),
    ]
