# Generated by Django 5.2 on 2025-05-14 02:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_alter_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True, verbose_name='订单号')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='购买数量')),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='购买时单价')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总价')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(choices=[('待支付', 'Unpaid'), ('已支付', 'Paid'), ('已取消', 'Canceled'), ('已发货', 'Shipped'), ('已完成', 'Completed')], default='待支付', max_length=20, verbose_name='订单状态')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='支付方式')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='支付交易号')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单列表',
                'ordering': ['-created_at'],
            },
        ),
    ]
